fix: TypeError when participant sends attachment(s)
send_file() now needs to return something,
and our subclass didn't, resulting in:

  File "/venv/lib/python3.11/site-packages/slidge/core/mixins/attachment.py", line 405, in send_files
    _url, msgs = await self.send_file(
    ^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object